export const IMAGEUPLOAD = 'IMAGEUPLOAD'
export const WRITE_SUCCESS = 'WRITE_SUCCESS'
export const WRITE_FAIL = 'WRITE_FAIL'
export const WRITE_REQUEST = 'WRITE_REQUEST'

//FIXME
export const WRITE_YESNO_REQUEST = 'WRITE_YESNO_REQUEST'
export const SUCCESS_WRITE_YESNO = 'SUCCESS_WRITE_YESNO'
