# Generated by Django 2.2.1 on 2019-06-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yesorno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
