# Generated by Django 2.1.7 on 2019-06-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yesorno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yesorno',
            old_name='candidate',
            new_name='candidateB',
        ),
    ]
