# Generated by Django 2.2.2 on 2019-06-04 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yesorno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='comment',
        ),
        migrations.AddField(
            model_name='usercomment',
            name='content',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='yesorno.YesOrNo'),
        ),
    ]
