# Generated by Django 2.2.1 on 2019-06-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yesorno', '0003_auto_20190604_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='like',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
