# Generated by Django 2.2.1 on 2019-06-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yesorno', '0004_auto_20190616_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='yesorno',
            name='candidate',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='yesorno',
            name='candidateA',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
