# Generated by Django 2.2.1 on 2019-06-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yesorno', '0005_auto_20190620_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yesorno',
            old_name='candidate',
            new_name='candidateB',
        ),
    ]
