export const PROFILE__REQUESTED = 'PROFILE__REQUESTED';

export const PROFILE__REQUESTED__SUCCEEDED = 'PROFILE__REQUESTED__SUCCEEDED';

export const PROFILE__REQUESTED__FAILED = 'PROFILE__REQUESTED__FAILED';

